name: 更新关键指标

# 触发条件
on:
  workflow_call:
  workflow_dispatch:

jobs:  
  gjzb0:
    runs-on: ubuntu-latest
    steps:      
      - name: 迁出代码
        uses: eshion/clone-github-repo-action@main
        with:
          owner: 'eshion'
          repository: 'stock'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
        env:
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
      - name: 加载缓存
        uses: actions/cache@v3
        with:
          path: ~/stock
          key: stock-gjzb0-${{ github.run_id }}
          restore-keys: stock-gjzb0-
      - name: 加载缓存-yjyg
        uses: actions/cache/restore@v3
        with:
          path: ~/stock
          key: stock-yjyg-${{ github.run_id }}
          restore-keys: stock-yjyg-
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: 安装依赖
        run: |
          cd stock
          pip install -r requirements.txt
      - name: 执行任务
        env:
          ENV_START: '0'
        run: |
          cd stock
          touch data/关键指标0.db
          python tools/get_latest_gjzb.py
      - name: 移到缓存
        run: |
          mkdir -p ~/stock
          cp stock/data/关键指标0.db ~/stock
  gjzb3:
    runs-on: ubuntu-latest
    steps:      
      - name: 迁出代码
        uses: eshion/clone-github-repo-action@main
        with:
          owner: 'eshion'
          repository: 'stock'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
        env:
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
      - name: 加载缓存
        uses: actions/cache@v3
        with:
          path: ~/stock
          key: stock-gjzb3-${{ github.run_id }}
          restore-keys: stock-gjzb3-
      - name: 加载缓存-yjyg
        uses: actions/cache/restore@v3
        with:
          path: ~/stock
          key: stock-yjyg-${{ github.run_id }}
          restore-keys: stock-yjyg-
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: 安装依赖
        run: |
          cd stock
          pip install -r requirements.txt
      - name: 执行任务
        env:
          ENV_START: '3'
        run: |
          cd stock
          touch data/关键指标3.db
          python tools/get_latest_gjzb.py
      - name: 移到缓存
        run: |
          mkdir -p ~/stock
          cp stock/data/关键指标3.db ~/stock
  gjzb6:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: eshion/clone-github-repo-action@main
        with:
          owner: 'eshion'
          repository: 'stock'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
        env:
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
      - name: 加载缓存
        uses: actions/cache@v3
        with:
          path: ~/stock
          key: stock-gjzb6-${{ github.run_id }}
          restore-keys: stock-gjzb6-
      - name: 加载缓存-yjyg
        uses: actions/cache/restore@v3
        with:
          path: ~/stock
          key: stock-yjyg-${{ github.run_id }}
          restore-keys: stock-yjyg-
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: 安装依赖
        run: |
          cd stock
          pip install -r requirements.txt
      - name: 执行任务
        env:
          ENV_START: '6'
        run: |
          cd stock
          touch data/关键指标6.db
          python tools/get_latest_gjzb.py
      - name: 移到缓存
        run: |
          mkdir -p ~/stock
          cp stock/data/关键指标6.db ~/stock  
  gjzb8:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: eshion/clone-github-repo-action@main
        with:
          owner: 'eshion'
          repository: 'stock'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
        env:
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
      - name: 加载缓存
        uses: actions/cache@v3
        with:
          path: ~/stock
          key: stock-gjzb8-${{ github.run_id }}
          restore-keys: stock-gjzb8-
      - name: 加载缓存-yjyg
        uses: actions/cache/restore@v3
        with:
          path: ~/stock
          key: stock-yjyg-${{ github.run_id }}
          restore-keys: stock-yjyg-
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: 安装依赖
        run: |
          cd stock
          pip install -r requirements.txt
      - name: 执行任务
        env:
          ENV_START: '8'
        run: |
          cd stock
          touch data/关键指标8.db
          python tools/get_latest_gjzb.py
      - name: 移到缓存
        run: |
          mkdir -p ~/stock
          cp stock/data/关键指标8.db ~/stock  
  gjzb:
    runs-on: ubuntu-latest
    needs:
      - gjzb0
      - gjzb3
      - gjzb6
      - gjzb8
    steps:
      - name: 迁出代码
        uses: eshion/clone-github-repo-action@main
        with:
          owner: 'eshion'
          repository: 'stock'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
        env:
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
      - name: 加载缓存
        uses: actions/cache@v3
        with:
          path: ~/stock
          key: stock-gjzb-${{ github.run_id }}
          restore-keys: stock-gjzb-
      - name: 加载缓存
        uses: actions/cache/restore@v3
        with:
          path: ~/stock
          key: stock-gjzb0-${{ github.run_id }}
          restore-keys: stock-gjzb0-
      - name: 加载缓存
        uses: actions/cache/restore@v3
        with:
          path: ~/stock
          key: stock-gjzb3-${{ github.run_id }}
          restore-keys: stock-gjzb3-
      - name: 加载缓存
        uses: actions/cache/restore@v3
        with:
          path: ~/stock
          key: stock-gjzb6-${{ github.run_id }}
          restore-keys: stock-gjzb6-
      - name: 加载缓存
        uses: actions/cache/restore@v3
        with:
          path: ~/stock
          key: stock-gjzb8-${{ github.run_id }}
          restore-keys: stock-gjzb8-
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: 安装依赖
        run: |
          cd stock
          pip install -r requirements.txt
      - name: 执行任务
        env:
          # ENV_START: '0,6'
          ENV_MERGE: true
        run: |
          cd stock
          ls -al ~/stock/
          cp -rf ~/stock/* data/
          touch data/关键指标.db
          python tools/get_latest_gjzb.py
      - name: 移到缓存
        run: |
          rm -rf ~/stock
          mkdir -p ~/stock
          cp stock/data/关键指标.db ~/stock
          ls -al ~/stock/