name: 更新关键指标

# 触发条件
on:
  workflow_dispatch:
  # 定时触发，UTC->Beijing 00:00->08:00
  # schedule:
  #   - cron: '30 16 * * *'

jobs:  
  gjzb0:
    # This job is currently disabled
    runs-on: ubuntu-latest
    steps:      
      - name: 迁出代码
        uses: eshion/clone-github-repo-action@main
        with:
          owner: 'eshion'
          repository: 'stock'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
        env:
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
      - name: 加载缓存
        uses: actions/cache@v3
        with:
          path: ~/stock
          key: stock-${{ github.run_id }}-gjzb0
          restore-keys: |
            ${{ runner.os }}-stock-gjzb0
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: 安装依赖
        run: |
          cd stock
          pip install -r requirements.txt
      - name: 执行任务
        env:
          ENV_START: '0'
        run: |
          cd stock
          python tools/get_latest_gjzb.py
      - name: 移到缓存
        run: |
          mkdir -p ~/stock
          cp stock/data/关键指标0.db ~/stock
  gjzb3:
    # This job is currently disabled
    runs-on: ubuntu-latest
    steps:      
      - name: 迁出代码
        uses: eshion/clone-github-repo-action@main
        with:
          owner: 'eshion'
          repository: 'stock'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
        env:
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
      - name: 加载缓存
        uses: actions/cache@v3
        with:
          path: ~/stock
          key: stock-${{ github.run_id }}-gjzb3
          restore-keys: |
            ${{ runner.os }}-stock-gjzb3
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: 安装依赖
        run: |
          cd stock
          pip install -r requirements.txt
      - name: 执行任务
        env:
          ENV_START: '3'
        run: |
          cd stock
          python tools/get_latest_gjzb.py
      - name: 移到缓存
        run: |
          mkdir -p ~/stock
          cp stock/data/关键指标3.db ~/stock
  gjzb6:
    # This job is currently disabled
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: eshion/clone-github-repo-action@main
        with:
          owner: 'eshion'
          repository: 'stock'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
        env:
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
      - name: 加载缓存
        uses: actions/cache@v3
        with:
          path: ~/stock
          key: stock-${{ github.run_id }}-gjzb6
          restore-keys: |
            ${{ runner.os }}-stock-gjzb6
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: 安装依赖
        run: |
          cd stock
          pip install -r requirements.txt
      - name: 执行任务
        env:
          ENV_START: '6'
        run: |
          cd stock
          python tools/get_latest_gjzb.py
      - name: 移到缓存
        run: |
          mkdir -p ~/stock
          cp stock/data/关键指标6.db ~/stock  
  gjzb:
    runs-on: ubuntu-latest
    # needs:
    #   - gjzb0
    #   - gjzb3
    #   - gjzb6
    steps:
      - name: 迁出代码
        uses: eshion/clone-github-repo-action@main
        with:
          owner: 'eshion'
          repository: 'stock'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
        env:
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
      - name: 加载缓存
        uses: actions/cache@v3
        with:
          path: ~/stock
          key: stock-${{ github.run_id }}-gjzb
          restore-keys: |
            ${{ runner.os }}-stock-gjzb
      - name: 加载缓存
        uses: actions/cache/restore@v3
        with:
          path: ~/stock
          key: stock-${{ github.run_id }}-gjzb0
          restore-keys: ${{ runner.os }}-stock-gjzb0
      - name: 加载缓存
        uses: actions/cache/restore@v3
        with:
          path: ~/stock
          key: stock-${{ github.run_id }}-gjzb3
          restore-keys: ${{ runner.os }}-stock-gjzb3
      - name: 加载缓存
        uses: actions/cache/restore@v3
        with:
          path: ~/stock
          key: stock-${{ github.run_id }}-gjzb6
          restore-keys: |
            ${{ runner.os }}-stock-gjzb6
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: 安装依赖
        run: |
          cd stock
          pip install -r requirements.txt
      - name: 执行任务
        env:
          # ENV_START: '0,6'
          ENV_MERGE: true
        run: |
          cd stock
          ls -al ~/stock/
          cp -rf ~/stock/* data/
          python tools/get_latest_gjzb.py
      - name: 移到缓存
        run: |
          rm -rf ~/stock
          mkdir -p ~/stock
          cp stock/data/关键指标.db ~/stock