name: 更新盈利预测

# 触发条件
on:
  workflow_dispatch:
  # 定时触发，UTC->Beijing 00:00->08:00
  # schedule:
  #   - cron: '30 16 * * *'

jobs:
  ylyc:
    runs-on: ubuntu-latest
    steps:      
      - name: 迁出代码
        uses: eshion/clone-github-repo-action@main
        with:
          owner: 'eshion'
          repository: 'stock'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - name: 加载缓存
        uses: actions/cache@v3
        with:
          path: ~/stock
          key: stock-ylyc-${{ github.run_id }}
          restore-keys: stock-ylyc-
      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
        env:
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: 安装依赖
        run: |
          cd stock
          pip install -r requirements.txt
      - name: 执行任务
        run: |
          cd stock
          python tools/get_stock_profit_forecast_ths.py
      - name: 移到缓存
        run: |
          mkdir -p ~/stock
          cp stock/data/盈利预测.db ~/stock
          ls -al ~/stock
