name: 合并数据到本地

# 触发条件
on:
  workflow_dispatch:
  # 定时触发，UTC->Beijing 00:00->08:00
  # schedule:
  #   - cron: '30 20 * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: eshion/clone-github-repo-action@main
        with:
          owner: 'eshion'
          repository: 'stock'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
        env:
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
      - name: 加载缓存
        uses: actions/cache/restore@v3
        with:
          path: ~/stock
          key: stock-${{ github.run_id }}-gjzb
          restore-keys: |
            ${{ runner.os }}-stock-gjzb
      - name: 加载缓存
        uses: actions/cache/restore@v3
        with:
          path: ~/stock
          key: stock-${{ github.run_id }}-cwzb_hk
          restore-keys: |
            ${{ runner.os }}-stock-cwzb_hk
      - name: 加载缓存
        uses: actions/cache/restore@v3
        with:
          path: ~/stock
          key: stock-${{ github.run_id }}-fhps
          restore-keys: |
            ${{ runner.os }}-stock-fhps
      - name: 加载缓存
        uses: actions/cache/restore@v3
        with:
          path: ~/stock
          key: stock-${{ github.run_id }}-fhps_hk
          restore-keys: |
            ${{ runner.os }}-stock-fhps_hk
      - name: 加载缓存
        uses: actions/cache/restore@v3
        with:
          path: ~/stock
          key: stock-${{ github.run_id }}-lszf
          restore-keys: |
            ${{ runner.os }}-stock-lszf
      - name: 加载缓存
        uses: actions/cache/restore@v3
        with:
          path: ~/stock
          key: stock-${{ github.run_id }}-ggxx
          restore-keys: |
            ${{ runner.os }}-stock-ggxx
      - name: 加载缓存
        uses: actions/cache/restore@v3
        with:
          path: ~/stock
          key: stock-${{ github.run_id }}-ylyc
          restore-keys: |
            ${{ runner.os }}-stock-ylyc
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: 安装依赖
        run: |
          cd stock
          pip install -r requirements.txt
      - name: 执行任务
        run: |
          cd stock
          ls -al ~/stock/
          cp -rf ~/stock/* data/
          python tools/merge_to_stock.py
      - name: 提交更改
        run: |
          cd stock
          git config core.ignorecase false
          git config --global credential.helper cache
          git config --local user.email "eshion@qq.com"
          git config --local user.name "eshion"
          git add .
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S')合并分支数据"
          git pull
          git push -f
