name: 合并数据到本地

# 触发条件
on:
  workflow_dispatch:
  # 定时触发，UTC->Beijing 00:00->08:00
  schedule:
    - cron: '30 20 * * *'

jobs:
    
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: 迁出代码
        uses: eshion/clone-github-repo-action@main
        with:
          owner: 'eshion'
          repository: 'stock'
          access-token: ${{ secrets.ACCESS_TOKEN }}  
      - name: 合并分支
        run: |
          cd stock
          git config core.ignorecase false
          git config --global credential.helper cache
          git config --local user.email "eshion@qq.com"
          git config --local user.name "eshion"
          git fetch origin
          git branch -a
          git checkout main
          git merge origin/个股信息 origin/历史涨幅 origin/分红配送 origin/分红配送HK origin/业绩报表 origin/资产负债表 origin/盈利预测 origin/财务指标HK 
      - name: 安装Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        env:
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
      - name: 加载缓存
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: 安装依赖
        run: |
          cd stock
          pip install -r requirements.txt
      - name: 执行任务
        run: |
          cd stock
          python tools/merge_to_stock.py
      - name: 提交更改
        run: |
          cd stock
          git config core.ignorecase false
          git config --global credential.helper cache
          git config --local user.email "eshion@qq.com"
          git config --local user.name "eshion"
          git add .
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S')合并分支数据"
          git pull
          git push -f
