name: Stock
on:
  workflow_dispatch:
  # 定时触发，UTC->Beijing 增加8小时得到北京时间
  # * 1 * * * -> 09:00
  schedule:
    - cron: '26 19 * * *'
jobs:
  gjzb:
    needs: yjyg
    uses: ./.github/workflows/get_stock_gjzb.yml
  cwzb_hk:
    uses: ./.github/workflows/get_stock_cwzb_hk.yml
  fhps:
    uses: ./.github/workflows/get_stock_fhps.yml
  fhps_hk:
    uses: ./.github/workflows/get_stock_fhps_hk.yml
  lszf:
    uses: ./.github/workflows/get_stock_lszf.yml
  ggxx:
    uses: ./.github/workflows/get_stock_ggxx.yml
  ylyc:
    needs: gjzb
    uses: ./.github/workflows/get_stock_ylyc.yml
  ylyc_hk:
    needs: cwzb_hk
    uses: ./.github/workflows/get_stock_ylyc_hk.yml
  yjkb:
    uses: ./.github/workflows/get_stock_yjkb.yml
  yjyg:
    uses: ./.github/workflows/get_stock_yjyg.yml
  jjcc:
    uses: ./.github/workflows/get_stock_jjcc.yml
  merge:
    needs:
      - gjzb
      - cwzb_hk
      - fhps
      - fhps_hk
      - lszf
      - ggxx
      - ylyc
      - ylyc_hk
      - yjkb
      - yjyg
      - jjcc
    uses: ./.github/workflows/merge_to_stock.yml