name: My Workflow

on:
  workflow_dispatch:
  # 定时触发，UTC->Beijing 00:00->08:00
  # schedule:
    # - cron: '30 16 * * *'
jobs:
  setup1:
    runs-on: ubuntu-latest

    steps:
    - name: Generate file 1
      run: echo "This is file 1" > /tmp/file1.txt

    - name: Cache file 1
      uses: actions/cache@v2
      with:
        path: /tmp/file1.txt
        key: ${{ runner.os }}-file1-${{ hashFiles('/tmp/file1.txt') }}
        restore-keys: |
          ${{ runner.os }}-file1-

  setup2:
    runs-on: ubuntu-latest

    steps:
    - name: Generate file 2
      run: echo "This is file 2" > /tmp/file2.txt

    - name: Cache file 2
      uses: actions/cache@v2
      with:
        path: /tmp/file2.txt
        key: ${{ runner.os }}-file2-${{ hashFiles('/tmp/file2.txt') }}
        restore-keys: |
          ${{ runner.os }}-file2-

  build:
    runs-on: ubuntu-latest
    needs:
      - setup1
      - setup2

    steps:
    - name: Restore files from cache
      uses: actions/cache@v2
      with:
        path: |
          /tmp/file1.txt
          /tmp/file2.txt
        key: ${{ runner.os }}-files-${{ hashFiles('/tmp/file1.txt','/tmp/file2.txt') }}
        restore-keys: |
          ${{ runner.os }}-file1-
          ${{ runner.os }}-file2-

    - name: Read file 1
      run: |
        if [ -f /tmp/file1.txt ]; then
          cat /tmp/file1.txt
        else
          echo "File 1 does not exist"
        fi

    - name: Read file 2
      run: |
        if [ -f /tmp/file2.txt ]; then
          cat /tmp/file2.txt
        else
          echo "File 2 does not exist"
        fi