name: My Workflow

on:
  workflow_dispatch:
  # 定时触发，UTC->Beijing 00:00->08:00
  # schedule:
    # - cron: '30 16 * * *'
jobs:
  zcfz:
    runs-on: ubuntu-latest
    steps:      
      - name: 迁出代码
        uses: eshion/clone-github-repo-action@main
        with:
          owner: 'eshion'
          repository: 'stock'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - name: 安装Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        env:
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
      - name: 加载缓存
        uses: actions/cache@v3
        with:
          path: ~/stock
          key: ${{ runner.os }}-stock-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-stock
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: 安装依赖
        run: |
          cd stock
          pip install -r requirements.txt
      - name: 执行任务
        env:
          ENV_START: '0'
        run: |
          cd stock
          python tools/get_latest_gjzb.py
      - name: 移到缓存
        run: |
          mkdir -p ~/stock
          cp stock/data/资产负债表.db ~/stock
  merge:
    runs-on: ubuntu-latest
    needs:
      - zcfz
    steps:
    - name: Cache file
      uses: actions/cache@v3
      with:
        path: ~/stock
        key: ${{ runner.os }}-stock-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-stock
    - name: read file
      run: |
        ls -al ~/stock