name: My Workflow

on:
  workflow_dispatch:
  # 定时触发，UTC->Beijing 00:00->08:00
  # schedule:
    # - cron: '30 16 * * *'
jobs:
  setup1:
    runs-on: ubuntu-latest

    steps:
    - name: Cache file 1
      uses: actions/cache@v3
      with:
        path: ~/stock
        key: ${{ runner.os }}-stock-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-stock
    - name: Generate file 1
      run: |
        mkdir ~/stock
        cat ~/stock/file1.txt
        echo "This is file 1" > ~/stock/file1.txt

  setup2:
    runs-on: ubuntu-latest
    - name: Cache file 2
      uses: actions/cache@v3
      with:
        path: ~/stock
        key: ${{ runner.os }}-stock-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-stock
    - name: Generate file 2
      run: |
        mkdir ~/stock
        cat ~/stock/file2.txt
        echo "This is file 2" > ~/stock/file2.txt

  setup3:
    runs-on: ubuntu-latest
    needs:
      - setup1
      - setup2
    steps:
    - name: Cache file
      uses: actions/cache@v3
      with:
        path: ~/stock
        key: ${{ runner.os }}-stock-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-stock
    - name: read file
      run: |
        cat ~/stock/file1.txt
        cat ~/stock/file2.txt