name: 测试

# 触发条件
on:
  workflow_dispatch:
  # 定时触发，UTC->Beijing 00:00->08:00
  # schedule:
  #   - cron: '0 4 * * *'

jobs:
  
  setup1:
    runs-on: ubuntu-latest
    steps:
    - name: Generate file 1
      run: |
        mkdir -p ~/stock
        ls -al ~/stock
        # cat ~/stock/file1.txt
        echo "This is file 1" > ~/stock/file1.txt
    - name: Cache file 1
      uses: actions/cache/save@v3
      with:
        path: ~/stock
        key: stock-${{ github.run_id }}-setup1

  setup2:
    runs-on: ubuntu-latest
    steps:
    - name: Generate file 2
      run: |
        mkdir -p ~/stock
        ls -al ~/stock
        # cat ~/stock/file2.txt
        echo "This is file 2" > ~/stock/file2.txt
    - name: Cache file 2
      uses: actions/cache/save@v3
      with:
        path: ~/stock
        key: stock-${{ github.run_id }}-setup2

  setup3:
    runs-on: ubuntu-latest
    needs:
      - setup1
      - setup2
    steps:
    - name: Cache file
      uses: actions/cache/restore@v3
      with:
        path: ~/stock
        key: stock-${{ github.run_id }}-setup1
    - name: read file
      run: |
        ls -al ~/stock
    - name: Cache file
      uses: actions/restore@v3
      with:
        path: ~/stock
        key: stock-${{ github.run_id }}-setup2
    - name: read file
      run: |
        ls -al ~/stock
        rm -rf ~/stock
        mkdir -p ~/stock
        echo "This is file 3" > ~/stock/file3.txt
    - name: Cache file 3
      uses: actions/cache/save@v3
      with:
        path: ~/stock
        key: stock-${{ github.run_id }}-setup3
  setup:
    runs-on: ubuntu-latest
    needs:
      - setup3
    steps:
    - name: Cache file
      uses: actions/cache/restore@v3
      with:
        path: ~/stock
        key: stock-${{ github.run_id }}-setup3
    - name: read file
      run: |
        ls -al ~/stock/
        