name: 测试

# 触发条件
on:
  workflow_dispatch:
  # 定时触发，UTC->Beijing 00:00->08:00
  # schedule:
  #   - cron: '0 4 * * *'

jobs:
  
  setup1:
    runs-on: ubuntu-latest
    steps:
    - name: Cache file 1
      uses: actions/cache@v3
      with:
        path: ~/stock
        key: ${{ runner.os }}-stock-setup1-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-stock-setup1
    - name: Generate file 1
      run: |
        mkdir -p ~/stock
        # cat ~/stock/file1.txt
        echo "This is file 1" > ~/stock/file1.txt

  setup2:
    runs-on: ubuntu-latest
    steps:
    - name: Cache file 2
      uses: actions/cache@v3
      with:
        path: ~/stock
        key: ${{ runner.os }}-stock-setup2-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-stock-setup2
    - name: Generate file 2
      run: |
        mkdir -p ~/stock
        # cat ~/stock/file2.txt
        echo "This is file 2" > ~/stock/file2.txt

  setup中文:
    runs-on: ubuntu-latest
    needs:
      - setup1
      - setup2
    steps:
    - name: Cache file
      uses: actions/cache@v3
      with:
        path: ~/stock
        key: ${{ runner.os }}-stock-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-stock-setup1
          ${{ runner.os }}-stock-setup2
    - name: read file
      run: |
        cat ~/stock/file1.txt
        cat ~/stock/file2.txt